### PR TITLE
primitive iteration & benchdnn

### PR DESCRIPTION
**Pull request by kruus**
This is a largish patch, mostly for iterating over primitives, esp. for benchdnn.  It is a subset of my [gen-dnn](https://github.com/necla-ml/gen-dnn) fork for non-JIT platforms.
- Fix primitive iterator **bug** (double-delete when iterating through all impls and then destroying the primitive iterator would usually segfault). Closes [issue 129](https://github.com/01org/mkl-dnn/issues/129)
  - add iteration example to `tests/api.c`
  - benchdnn heavily modified to iterate over impls (now `--skip-impls` is usable as previously documented)
    - benchdnn may run all impls, so memory cleanup on error significantly tightened.
      - early return macros `SAFE` and `DNN_SAFE` --> scoped objects or lambdas to properly free mem
      - dnn_mem_t also changed (mainly constructor & destructor safety issues)
    - benchdnn iteration adds `--mode=A` to run *All* impls, not just existing "best/first" impl
      - also 'T' option for alt. benchdnn ref impls [none of which exist yet]
    - benchdnn PERF default output adds extra \%i field with short impl name
    - benchdn docs updated
- Many misc doxygen touchups and typos
- Some benign `#ifdef`ed OS tweaks for SX

Review items (need help with these)

- [ ] Check win32 compile and tests
- [ ] Check icc compile and tests
- [ ] check size_t issues (esp. cpu/ref_convolution.cpp cpu/ref_eltwise.cpp cpu/ref_inner_product.cpp cpu/simple_reorder.hpp). There are many conversion warnings again, but it's not within main scope of this patch.
- [ ] code consistency / formatting / Copyright (a few new files)

Review items that I'll look at shortly:
- [x] remove benchdnn dead code
- [x] check doxygen output again (did I add *other .md files* in this PR?)
  - not important, because PR does not modify Doxy/cmake to produce/install developer docs.
- [x] `reorder()` still looks like it might leak resources for error conditions (double-check all `*SAFE(X,WARN)` usages, in general, for resource leakage)
- [x] bench.sh/build.sh might be generally useful, but might also just be clutter

Erik

### CODE REVIEW

**Comment by emfomenk** [comment]
Hi @kruus,

Too many things... looks scary :) 

I definitely like some of the things (some other I still should realize).
But I would like to reorganize the patch-set into several smaller one, with logical self-contained change per commit.  Please give me some time to understand how we should proceed.

Meanwhile I will put some comments so that either you or someone else from our team may address them.

**Comment by emfomenk** [comment]
Would you mind if you and i would "push --force" into this branch rewriting the history (split those patches into several smaller logically compete ones)?
Alternatively we can create another branch and do that there, so that nothing is lost.

**Comment by kruus** [comment]
I don't mind at all. Could easily split, for example, into:
- critical bugfix
- test/api.c "example" of iteration (could be a separate demo, even)
- benchdnn mods (benchdnn output is mostly same as before, so benign)
- documentation updates.
- benign changes (nobody hurt, but helps what I need to do in some small way)

**Comment by emfomenk** [comment]
Sounds good.
I will do some initial work later today (hopefully)...

**Comment by kruus** [comment]
Leave any serious mods to `benchdnn/` + iterator stuff until next Tuesday, ok? I want to look at (esp.) benchdnn/conv.cpp *with fresh eyes* on Monday.

**Comment by emfomenk** [comment]
Sure, will focus on src/ and include/ then

**Comment by kruus** [comment]
benchdnn shorten(impl_str) now reports target cpu. Commented about why enum cpu_isa_t might be useful to expose in `mkldnn.h` (even this fork's `cpu_isa.hpp` internal header has not really moved visibility up [from jit/] enough).
Q: Was there some issue with WIN32 and size_t loop indices?  I recall comments, but not the issue. Afaik, only some really old openmp required `int` loop indices, which might a valid reason to avoid `size_t` (or `ssize_t`/`ptrdiff_t`) in some cases.

**Comment by kruus** [comment]
oh, there was a question in code about correctness of compute_pad in conv_aux. While technically correct, I now add one before dividing by two.  Rounding pad values upward means that compute_pad followed by compute_out guarantees never to ask for a smaller output size.  In particular, round pad upward avoids changing a desired output size of 1 to an output size of 0, which is a FAIL for init_mem_desc.

**Comment by kruus** [comment]
This PR is getting stale.  My own benchdnn code is now more polished, and I've done an upstream merge on my gen-dnn fork. Probably not worth resolving conflicts. Close at will.

**Comment by emfomenk** [comment]
Sorry for being stuck with PR. Too many changes happened in parallel.
I would like to keep the PR alive for some time and will manually port some changes from it. You did great job and I don't want to lose that.

Quick heads up. Benchdnn code is being changed a lot nowadays. We are adding new API for some int8-inference support (such as primitive scaling and fusion capabilities). Attributes and post-ops are devoted for that. You have already found a bug with attributes in a separate thread :)

**Comment by kruus** [comment]
attributes and post-ops have changed my benchdnn iterator code non-trivially from what is here. This PR seems like just noise, at this time.

**Comment by emfomenk** [comment]
Yeah, you are right. Closing it.

Just a quick note -- we also start thinking we have iterate over different implementations in benchdnn to cover more cases. Once we finally decide implementing that -- I will take a look on what you have in gen-dnn...

Anyway, thanks for your contributions! :)

**Comment by kruus** [comment]
Yup, that's a good way to go for --mode=All testing.  I cleaned up some major ugliness for that this afternoon, stuff I've been meaning to get to for ages.

**Pull request closed without merging**
