### PR TITLE
Add engine query in C++ interface

### PR DESCRIPTION
**Pull request by 4pao**
Signed-off-by: caozhong <zhong.z.cao@intel.com>

### CODE REVIEW

**Comment by emfomenk** [comment]
Hi @4pao,

Thanks, the change makes sense. Few comments though:

1. At this moment we use 4 space indentation. Could you please adjust? 
2. Does it make sense to implement template-based get_engine() function that will be a friend to all primitive::primitive_desc's? That should substantially reduce the amount of code...

**Comment by 4pao** [comment]
Good point, at start I thought only memory interface needed get_engine query. Because most of the time we create computational primitive based on where memory was. But may be for complementation reason, it might let all primitive_desc have it. For less code, I upstreamed a few more choice.

1. Constructor from primitive_desc, using like "engine new_engine(src_pd)"
2. Static query in engine class, create engine weak reference based on primitive_desc, like a factory
3. Template form, like 2. using like "new_e = engine::query(src_pd)"

All work, one should do all work.

**Comment by 4pao** [comment]
Fix a little error. And const for rvalues and spiritual.

**Comment by emfomenk** [comment]
Hi @pao,

Sorry for delay...

Could you please review the changes I did and confirm whether you are oK with them?
If yes, I will then merge the changes to master.

**Comment by pao** [comment]
@4pao (not me!), see above from @emfomenk.

**Comment by emfomenk** [comment]
Sorry, that's typo :)

**Comment by 4pao** [comment]
All good. Thanks!

**Pull request merged**
