### PR TITLE
mkl-dnn windows port

### PR DESCRIPTION
**Pull request by guschmue**
Initial cut at mkl-dnn windows port.
Both msvc and intel compiler build and pass unittest but because of the missing openmp v3
support in msvc we can not enable openmp.

Issues: the unittest test_convolution_backward_data
BackwardData_SimpleSmall_Blocked/convolution_test.TestConvolution/5 is flaky.

Most of the port deals with the following:
1. win64abi
2. windows platform specific functions, like posix_memalign
3. msvc specifics

We have tested sse4 and avx2. 
Performance looks similar to linux for unittests.

### CODE REVIEW

**Comment by guschmue** [comment]
This should address the windows part of https://github.com/01org/mkl-dnn/issues/10

**Comment by emfomenk** [comment]
Thanks for PR! All the changes look reasonable to me.

We most likely would avoid using alloca (will just use heap allocation instead).
The rest looks more or less similar to what we have. Please give us ~1 week to clean and prettify all the stuff and promote Win support to the master.

Could you please say what Cmake, MSVS and ICL versions you use?

Thank you a lot for the contribution!

**Comment by guschmue** [comment]
I was very split on the alloca() / stl::vector as well. Performance was the same and unit test passed for both but yes, heap is the safer option.
I use vs2015, cmake3.8 and icl 17.  
vs2017 works too but does not integrate with icl 17, that is why I didn't use it.
Anyway, let me know if I can help with something!

**Comment by vpirogov** [comment]
Windows support is now available in master. Thanks again for your contribution.

**Pull request closed without merging**
